/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Find all users paginated response. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: {
                                address?: {
                                    city: string;
                                    country: string;
                                    postalCode: string;
                                    street: string;
                                };
                                cart?: string[];
                                createdAt: string;
                                email: string;
                                favorites?: string[];
                                id: string;
                                isDisabled: boolean;
                                isVerified: boolean;
                                lastLoginAt?: string;
                                lastPasswordChangeAt?: string;
                                marketingOptIn?: boolean;
                                phone?: string;
                                refreshTokenVersion: number;
                                /** @enum {string} */
                                role: "admin" | "customer";
                                updatedAt?: string;
                                username?: string;
                            }[];
                            page: number;
                            limit: number;
                            total: number;
                            totalPages: number;
                        };
                    };
                };
                /** @description Unauthorized. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
                /** @description No resource found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Create user body. */
            requestBody: {
                content: {
                    "application/json": {
                        email: string;
                        password: string;
                        /** @enum {string} */
                        role: "admin" | "customer";
                    };
                };
            };
            responses: {
                /** @description Successful response. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            address?: {
                                city: string;
                                country: string;
                                postalCode: string;
                                street: string;
                            };
                            cart?: string[];
                            createdAt: string;
                            email: string;
                            favorites?: string[];
                            id: string;
                            isDisabled: boolean;
                            isVerified: boolean;
                            lastLoginAt?: string;
                            lastPasswordChangeAt?: string;
                            marketingOptIn?: boolean;
                            phone?: string;
                            refreshTokenVersion: number;
                            /** @enum {string} */
                            role: "admin" | "customer";
                            updatedAt?: string;
                            username?: string;
                        };
                    };
                };
                /** @description Unauthorized. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
                /** @description No resource found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            address?: {
                                city: string;
                                country: string;
                                postalCode: string;
                                street: string;
                            };
                            cart?: string[];
                            createdAt: string;
                            email: string;
                            favorites?: string[];
                            id: string;
                            isDisabled: boolean;
                            isVerified: boolean;
                            lastLoginAt?: string;
                            lastPasswordChangeAt?: string;
                            marketingOptIn?: boolean;
                            phone?: string;
                            refreshTokenVersion: number;
                            /** @enum {string} */
                            role: "admin" | "customer";
                            updatedAt?: string;
                            username?: string;
                        };
                    };
                };
                /** @description Unauthorized. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
                /** @description No resource found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            /** @description Update user body. */
            requestBody: {
                content: {
                    "application/json": {
                        address?: {
                            city: string;
                            country: string;
                            postalCode: string;
                            street: string;
                        };
                        email: string;
                        phone?: string;
                        username?: string;
                    };
                };
            };
            responses: {
                /** @description Successful response. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            address?: {
                                city: string;
                                country: string;
                                postalCode: string;
                                street: string;
                            };
                            cart?: string[];
                            createdAt: string;
                            email: string;
                            favorites?: string[];
                            id: string;
                            isDisabled: boolean;
                            isVerified: boolean;
                            lastLoginAt?: string;
                            lastPasswordChangeAt?: string;
                            marketingOptIn?: boolean;
                            phone?: string;
                            refreshTokenVersion: number;
                            /** @enum {string} */
                            role: "admin" | "customer";
                            updatedAt?: string;
                            username?: string;
                        };
                    };
                };
                /** @description Unauthorized. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
                /** @description No resource found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            address?: {
                                city: string;
                                country: string;
                                postalCode: string;
                                street: string;
                            };
                            cart?: string[];
                            createdAt: string;
                            email: string;
                            favorites?: string[];
                            id: string;
                            isDisabled: boolean;
                            isVerified: boolean;
                            lastLoginAt?: string;
                            lastPasswordChangeAt?: string;
                            marketingOptIn?: boolean;
                            phone?: string;
                            refreshTokenVersion: number;
                            /** @enum {string} */
                            role: "admin" | "customer";
                            updatedAt?: string;
                            username?: string;
                        };
                    };
                };
                /** @description Unauthorized. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
                /** @description No resource found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/email/{email}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    email: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            address?: {
                                city: string;
                                country: string;
                                postalCode: string;
                                street: string;
                            };
                            cart?: string[];
                            createdAt: string;
                            email: string;
                            favorites?: string[];
                            id: string;
                            isDisabled: boolean;
                            isVerified: boolean;
                            lastLoginAt?: string;
                            lastPasswordChangeAt?: string;
                            marketingOptIn?: boolean;
                            phone?: string;
                            refreshTokenVersion: number;
                            /** @enum {string} */
                            role: "admin" | "customer";
                            updatedAt?: string;
                            username?: string;
                        };
                    };
                };
                /** @description Unauthorized. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
                /** @description No resource found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/{id}/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            /** @description Update user password body. */
            requestBody: {
                content: {
                    "application/json": {
                        newPassword: string;
                    };
                };
            };
            responses: {
                /** @description Successful response. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            address?: {
                                city: string;
                                country: string;
                                postalCode: string;
                                street: string;
                            };
                            cart?: string[];
                            createdAt: string;
                            email: string;
                            favorites?: string[];
                            id: string;
                            isDisabled: boolean;
                            isVerified: boolean;
                            lastLoginAt?: string;
                            lastPasswordChangeAt?: string;
                            marketingOptIn?: boolean;
                            phone?: string;
                            refreshTokenVersion: number;
                            /** @enum {string} */
                            role: "admin" | "customer";
                            updatedAt?: string;
                            username?: string;
                        };
                    };
                };
                /** @description Unauthorized. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
                /** @description No resource found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/{id}/isVerified": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            /** @description Update user is verified body. */
            requestBody: {
                content: {
                    "application/json": {
                        isVerified: boolean;
                    };
                };
            };
            responses: {
                /** @description Successful response. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            address?: {
                                city: string;
                                country: string;
                                postalCode: string;
                                street: string;
                            };
                            cart?: string[];
                            createdAt: string;
                            email: string;
                            favorites?: string[];
                            id: string;
                            isDisabled: boolean;
                            isVerified: boolean;
                            lastLoginAt?: string;
                            lastPasswordChangeAt?: string;
                            marketingOptIn?: boolean;
                            phone?: string;
                            refreshTokenVersion: number;
                            /** @enum {string} */
                            role: "admin" | "customer";
                            updatedAt?: string;
                            username?: string;
                        };
                    };
                };
                /** @description Unauthorized. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
                /** @description No resource found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/{id}/isDisabled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            /** @description Update user is disabled body. */
            requestBody: {
                content: {
                    "application/json": {
                        isDisabled: boolean;
                    };
                };
            };
            responses: {
                /** @description Successful response. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            address?: {
                                city: string;
                                country: string;
                                postalCode: string;
                                street: string;
                            };
                            cart?: string[];
                            createdAt: string;
                            email: string;
                            favorites?: string[];
                            id: string;
                            isDisabled: boolean;
                            isVerified: boolean;
                            lastLoginAt?: string;
                            lastPasswordChangeAt?: string;
                            marketingOptIn?: boolean;
                            phone?: string;
                            refreshTokenVersion: number;
                            /** @enum {string} */
                            role: "admin" | "customer";
                            updatedAt?: string;
                            username?: string;
                        };
                    };
                };
                /** @description Unauthorized. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
                /** @description No resource found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/{id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            /** @description Update user role body. */
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        role: "admin" | "customer";
                    };
                };
            };
            responses: {
                /** @description Successful response. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            address?: {
                                city: string;
                                country: string;
                                postalCode: string;
                                street: string;
                            };
                            cart?: string[];
                            createdAt: string;
                            email: string;
                            favorites?: string[];
                            id: string;
                            isDisabled: boolean;
                            isVerified: boolean;
                            lastLoginAt?: string;
                            lastPasswordChangeAt?: string;
                            marketingOptIn?: boolean;
                            phone?: string;
                            refreshTokenVersion: number;
                            /** @enum {string} */
                            role: "admin" | "customer";
                            updatedAt?: string;
                            username?: string;
                        };
                    };
                };
                /** @description Unauthorized. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
                /** @description No resource found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/{id}/marketingOptIn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            /** @description Update user marketingOptIn body. */
            requestBody: {
                content: {
                    "application/json": {
                        marketingOptIn: boolean;
                    };
                };
            };
            responses: {
                /** @description Successful response. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            address?: {
                                city: string;
                                country: string;
                                postalCode: string;
                                street: string;
                            };
                            cart?: string[];
                            createdAt: string;
                            email: string;
                            favorites?: string[];
                            id: string;
                            isDisabled: boolean;
                            isVerified: boolean;
                            lastLoginAt?: string;
                            lastPasswordChangeAt?: string;
                            marketingOptIn?: boolean;
                            phone?: string;
                            refreshTokenVersion: number;
                            /** @enum {string} */
                            role: "admin" | "customer";
                            updatedAt?: string;
                            username?: string;
                        };
                    };
                };
                /** @description Unauthorized. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
                /** @description No resource found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/{id}/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            /** @description Update user favorites body. */
            requestBody: {
                content: {
                    "application/json": {
                        favorites: string[];
                    };
                };
            };
            responses: {
                /** @description Successful response. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            address?: {
                                city: string;
                                country: string;
                                postalCode: string;
                                street: string;
                            };
                            cart?: string[];
                            createdAt: string;
                            email: string;
                            favorites?: string[];
                            id: string;
                            isDisabled: boolean;
                            isVerified: boolean;
                            lastLoginAt?: string;
                            lastPasswordChangeAt?: string;
                            marketingOptIn?: boolean;
                            phone?: string;
                            refreshTokenVersion: number;
                            /** @enum {string} */
                            role: "admin" | "customer";
                            updatedAt?: string;
                            username?: string;
                        };
                    };
                };
                /** @description Unauthorized. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
                /** @description No resource found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/{id}/cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            /** @description Update user cart body. */
            requestBody: {
                content: {
                    "application/json": {
                        cart: string[];
                    };
                };
            };
            responses: {
                /** @description Successful response. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            address?: {
                                city: string;
                                country: string;
                                postalCode: string;
                                street: string;
                            };
                            cart?: string[];
                            createdAt: string;
                            email: string;
                            favorites?: string[];
                            id: string;
                            isDisabled: boolean;
                            isVerified: boolean;
                            lastLoginAt?: string;
                            lastPasswordChangeAt?: string;
                            marketingOptIn?: boolean;
                            phone?: string;
                            refreshTokenVersion: number;
                            /** @enum {string} */
                            role: "admin" | "customer";
                            updatedAt?: string;
                            username?: string;
                        };
                    };
                };
                /** @description Unauthorized. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
                /** @description No resource found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
